# SEO settings
title: "Slis ML"
# title2: "space" # default: ""
description: "筑波大学図書館情報メディア研究科/知識情報・図書館学類の機械学習系の集まりです"
# keywords: ""
# url: http://heiswayi.github.io/thinkspace # site url
# baseurl: "/" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
# repo: http://github.com/heiswayi/thinkspace
# disqus_shortname: "heiswayi"
# twitter_username: "HeiswayiNrird"
# comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

permalink: /:year/:month/:title

# Author settings
author:
  # name     : ""
  # job      : "R&D Software Engineer"
  bio      : "機械学習系の研究室の勉強会やゼミの日程をお知らせします"
  # thumb    : /images/author.jpg
  # email    : hnrird@gmail.com
  # url      : http://heiswayi.github.io
  # github   : http://github.com/heiswayi
  # twitter  : http://twitter.com/HeiswayiNrird
  # facebook : https://www.facebook.com/profile.php?id=1257583160
  # linkedin : http://linkedin.com/in/nrird

# social settings
# og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "vendor"]

future: true
timezone: JPN
